const galleryJS = [
    {   id: 1,
        src: 'src/assets/images/certificados/javascript/diploma-basico-javascript.png',
        title: 'Curso Basico JS',
        description: 'Diploma que certifica el curso de Curso Basico JS' },
    {   id: 2,
        src: 'src/assets/images/certificados/javascript/diploma-asincronismo-js.png',
        title: 'Javascript Asincronismo',
        description: 'Diploma que certifica el curso de Javascript Asincronismo' },
    {   id: 3,
        src: 'src/assets/images/certificados/javascript/diploma-ecmascript-6.png',
        title: 'Ecmascript 6',
        description: 'Diploma que certifica el curso de Ecmascript 6' },
    {   id: 4,
        src: 'src/assets/images/certificados/javascript/diploma-frontend-developer.png',
        title: 'Frontend Developer Javascript',
        description: 'Diploma que certifica el curso, Frontend Developer Javascript' },
    {   id: 5,
        src: 'src/assets/images/certificados/javascript/diploma-fundamentos-javascript.png',
        title: 'Fundamentos Javascript',
        description: 'Diploma que certifica el curso Fundamentos Javascript' },
    {   id: 6,
        src: 'src/assets/images/certificados/javascript/diploma-singlepage-app.png',
        title: 'Router para singles page app con Javascript',
        description: 'Diploma que certifica Responsive Design: Maquetación mobile first' },
    {   id: 7,
        src: 'src/assets/images/certificados/javascript/diploma-javascript-navegador.png',
        title: 'Javascript Engine v8',
        description: 'Diploma que certifica Javascript Engine v8' },
    {   id: 8,
        src: 'src/assets/images/certificados/javascript/diploma-javascript-profesional.png',
        title: 'Javascript Profesional',
        description: 'Diploma que certifica Javascript Profesional' },
    {   id: 9,
        src: 'src/assets/images/certificados/javascript/diploma-scope.png',
        title: 'Closures y Scope en Javascript',
        description: 'Diploma que certifica Closures y Scope en Javascript' },
    {   id: 10,
        src: 'src/assets/images/certificados/javascript/diploma-npm.png',
        title: 'Gestión de dependencias y paquetes con NPM',
        description: 'Diploma que certifica Gestión de dependencias y paquetes con NPM' },
    {   id: 11,
        src: 'src/assets/images/certificados/javascript/diploma-spa-javascript.png',
        title: 'Single page application con Javascript vanilla',
        description: 'Diploma que certifica Single page application con Javascript vanilla' },
    {   id: 12,
        src: 'src/assets/images/certificados/javascript/diploma-webpack.png',
        title: 'Webpack',
        description: 'Diploma que certifica Webpack' },
];

export default galleryJS;

