const galleryHtmlCSS = [
    {   id: 1,
        src: 'src/assets/images/certificados/htmlycss/diploma-html-css.png',
        title: 'HTML y CSS',
        description: 'Diploma que certifica el curso de HTML y CSS' },
    {   id: 2,
        src: 'src/assets/images/certificados/htmlycss/diploma-accesibilidad-web.png',
        title: 'Accesibilidad Web',
        description: 'Diploma que certifica el curso de Accesibilidad Web' },
    {   id: 3,
        src: 'src/assets/images/certificados/htmlycss/diploma-html-practico.png',
        title: 'HTML y CSS practico',
        description: 'Diploma que certifica el curso de HTML y CSS practico' },
    {   id: 4,
        src: 'src/assets/images/certificados/htmlycss/diploma-introweb.png',
        title: 'Introducción a la web: Historia y funcionamiento de Internet',
        description: 'Diploma que certifica el curso, Introducción a la web: Historia y funcionamiento de Internet' },
    {   id: 5,
        src: 'src/assets/images/certificados/htmlycss/diploma-css-grid-layout.png',
        title: 'CSS grid Layout',
        description: 'Diploma que certifica el curso, CSS grid Layou' },
    {   id: 6,
        src: 'src/assets/images/certificados/htmlycss/diploma-mobile-first.png',
        title: 'Responsive Design: Maquetación mobile first',
        description: 'Diploma que certifica Responsive Design: Maquetación mobile first' },
    {   id: 7,
        src: 'src/assets/images/certificados/htmlycss/diploma-responsive-design.png',
        title: 'Responsive Design',
        description: 'Diploma que certifica Responsive Design' },
    {   id: 8,
        src: 'src/assets/images/certificados/htmlycss/diploma-preprocesadores.png',
        title: 'Preprocesadores CSS',
        description: 'Diploma que certifica Preprocesadores CSS' },
    {   id: 9,
        src: 'src/assets/images/certificados/htmlycss/diploma-sass.png',
        title: 'Proprocesadores SASS',
        description: 'Diploma que certifica Proprocesadores SASS' },
];

export default galleryHtmlCSS;

